/* tslint:disable */
/* eslint-disable */
/**
 * 당근 미니 게임 API 문서
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Configuration } from './configuration';
import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from './base';

/**
 * 
 * @export
 * @interface BaseResponseListTownRankingDto
 */
export interface BaseResponseListTownRankingDto {
    /**
     * 
     * @type {Array<TownRankingDto>}
     * @memberof BaseResponseListTownRankingDto
     */
    'data'?: Array<TownRankingDto>;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseListTownRankingDto
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListTownRankingDto
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseListTownRankingDto
     */
    'timestamp': string;
}
/**
 * 
 * @export
 * @interface BaseResponseListUserRankingDto
 */
export interface BaseResponseListUserRankingDto {
    /**
     * 
     * @type {Array<UserRankingDto>}
     * @memberof BaseResponseListUserRankingDto
     */
    'data'?: Array<UserRankingDto>;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseListUserRankingDto
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseListUserRankingDto
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseListUserRankingDto
     */
    'timestamp': string;
}
/**
 * 
 * @export
 * @interface BaseResponseNotificationCheckDto
 */
export interface BaseResponseNotificationCheckDto {
    /**
     * 
     * @type {NotificationCheckDto}
     * @memberof BaseResponseNotificationCheckDto
     */
    'data'?: NotificationCheckDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseNotificationCheckDto
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseNotificationCheckDto
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseNotificationCheckDto
     */
    'timestamp': string;
}
/**
 * 
 * @export
 * @interface BaseResponseRankingDto
 */
export interface BaseResponseRankingDto {
    /**
     * 
     * @type {RankingDto}
     * @memberof BaseResponseRankingDto
     */
    'data'?: RankingDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseRankingDto
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseRankingDto
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseRankingDto
     */
    'timestamp': string;
}
/**
 * 
 * @export
 * @interface BaseResponseRegionDto
 */
export interface BaseResponseRegionDto {
    /**
     * 
     * @type {RegionDto}
     * @memberof BaseResponseRegionDto
     */
    'data'?: RegionDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseRegionDto
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseRegionDto
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseRegionDto
     */
    'timestamp': string;
}
/**
 * 
 * @export
 * @interface BaseResponseTokenDto
 */
export interface BaseResponseTokenDto {
    /**
     * 
     * @type {TokenDto}
     * @memberof BaseResponseTokenDto
     */
    'data'?: TokenDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseTokenDto
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseTokenDto
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseTokenDto
     */
    'timestamp': string;
}
/**
 * 
 * @export
 * @interface BaseResponseUnit
 */
export interface BaseResponseUnit {
    /**
     * 
     * @type {object}
     * @memberof BaseResponseUnit
     */
    'data'?: object;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUnit
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseUnit
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUnit
     */
    'timestamp': string;
}
/**
 * 
 * @export
 * @interface BaseResponseUserDto
 */
export interface BaseResponseUserDto {
    /**
     * 
     * @type {UserDto}
     * @memberof BaseResponseUserDto
     */
    'data'?: UserDto;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserDto
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseUserDto
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseUserDto
     */
    'timestamp': string;
}
/**
 * 
 * @export
 * @interface BaseResponseint
 */
export interface BaseResponseint {
    /**
     * 
     * @type {number}
     * @memberof BaseResponseint
     */
    'data'?: number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseint
     */
    'message'?: string;
    /**
     * 
     * @type {number}
     * @memberof BaseResponseint
     */
    'status': number;
    /**
     * 
     * @type {string}
     * @memberof BaseResponseint
     */
    'timestamp': string;
}
/**
 * 
 * @export
 * @interface CommentRequestDto
 */
export interface CommentRequestDto {
    /**
     * 
     * @type {string}
     * @memberof CommentRequestDto
     */
    'comment': string;
}
/**
 * 
 * @export
 * @interface KarrotCodeRequestDto
 */
export interface KarrotCodeRequestDto {
    /**
     * 
     * @type {string}
     * @memberof KarrotCodeRequestDto
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof KarrotCodeRequestDto
     */
    'regionId': string;
}
/**
 * 
 * @export
 * @interface NotificationCheckDto
 */
export interface NotificationCheckDto {
    /**
     * 
     * @type {boolean}
     * @memberof NotificationCheckDto
     */
    'check': boolean;
}
/**
 * 
 * @export
 * @interface NotificationRequestDto
 */
export interface NotificationRequestDto {
    /**
     * 
     * @type {string}
     * @memberof NotificationRequestDto
     */
    'type': NotificationRequestDtoTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum NotificationRequestDtoTypeEnum {
    OpenRegion = 'OPEN_REGION',
    OpenGame = 'OPEN_GAME',
    SubscribeOff = 'SUBSCRIBE_OFF'
}

/**
 * 
 * @export
 * @interface RankingDto
 */
export interface RankingDto {
    /**
     * 
     * @type {string}
     * @memberof RankingDto
     */
    'comment'?: string;
    /**
     * 
     * @type {number}
     * @memberof RankingDto
     */
    'rank': number;
    /**
     * 
     * @type {number}
     * @memberof RankingDto
     */
    'score': number;
}
/**
 * 
 * @export
 * @interface RegionDto
 */
export interface RegionDto {
    /**
     * 
     * @type {string}
     * @memberof RegionDto
     */
    'name1': string;
    /**
     * 
     * @type {string}
     * @memberof RegionDto
     */
    'name2': string;
    /**
     * 
     * @type {string}
     * @memberof RegionDto
     */
    'name3': string;
    /**
     * 
     * @type {string}
     * @memberof RegionDto
     */
    'townId': string;
}
/**
 * 
 * @export
 * @interface ScoreRequestDto
 */
export interface ScoreRequestDto {
    /**
     * 
     * @type {number}
     * @memberof ScoreRequestDto
     */
    'score'?: number;
}
/**
 * 
 * @export
 * @interface SurveyRequestDto
 */
export interface SurveyRequestDto {
    /**
     * 
     * @type {string}
     * @memberof SurveyRequestDto
     */
    'content': string;
    /**
     * 
     * @type {string}
     * @memberof SurveyRequestDto
     */
    'regionId': string;
}
/**
 * 
 * @export
 * @interface TokenDto
 */
export interface TokenDto {
    /**
     * 
     * @type {string}
     * @memberof TokenDto
     */
    'accessToken': string;
}
/**
 * 
 * @export
 * @interface TownDto
 */
export interface TownDto {
    /**
     * 
     * @type {string}
     * @memberof TownDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof TownDto
     */
    'name1': string;
    /**
     * 
     * @type {string}
     * @memberof TownDto
     */
    'name2': string;
}
/**
 * 
 * @export
 * @interface TownRankingDto
 */
export interface TownRankingDto {
    /**
     * 
     * @type {string}
     * @memberof TownRankingDto
     */
    'name1': string;
    /**
     * 
     * @type {string}
     * @memberof TownRankingDto
     */
    'name2': string;
    /**
     * 
     * @type {number}
     * @memberof TownRankingDto
     */
    'playerCount'?: number;
    /**
     * 
     * @type {number}
     * @memberof TownRankingDto
     */
    'score': number;
}
/**
 * 
 * @export
 * @interface UserDto
 */
export interface UserDto {
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof UserDto
     */
    'nickname': string;
    /**
     * 
     * @type {TownDto}
     * @memberof UserDto
     */
    'town': TownDto;
}
/**
 * 
 * @export
 * @interface UserRankingDto
 */
export interface UserRankingDto {
    /**
     * 
     * @type {string}
     * @memberof UserRankingDto
     */
    'comment'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRankingDto
     */
    'nickname': string;
    /**
     * 
     * @type {number}
     * @memberof UserRankingDto
     */
    'score': number;
    /**
     * 
     * @type {TownDto}
     * @memberof UserRankingDto
     */
    'town': TownDto;
    /**
     * 
     * @type {string}
     * @memberof UserRankingDto
     */
    'userId'?: string;
}

/**
 * GamePlayApi - axios parameter creator
 * @export
 */
export const GamePlayApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 한마디 추가
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {CommentRequestDto} requestDto requestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addCommentUsingPATCH: async (gameType: 'GAME_KARROT' | 'GAME_2048', requestDto: CommentRequestDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'gameType' is not null or undefined
            assertParamExists('addCommentUsingPATCH', 'gameType', gameType)
            // verify required parameter 'requestDto' is not null or undefined
            assertParamExists('addCommentUsingPATCH', 'requestDto', requestDto)
            const localVarPath = `/api/games/{gameType}/comment`
                .replace(`{${"gameType"}}`, encodeURIComponent(String(gameType)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 2시간 내에 플레이한 유저 수
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCountByDailyUsingGET: async (gameType: 'GAME_KARROT' | 'GAME_2048', options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'gameType' is not null or undefined
            assertParamExists('getUserCountByDailyUsingGET', 'gameType', gameType)
            const localVarPath = `/api/games/{gameType}/play/daily-count`
                .replace(`{${"gameType"}}`, encodeURIComponent(String(gameType)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 플레이
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        playGameUsingPOST: async (gameType: 'GAME_KARROT' | 'GAME_2048', options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'gameType' is not null or undefined
            assertParamExists('playGameUsingPOST', 'gameType', gameType)
            const localVarPath = `/api/games/{gameType}/play`
                .replace(`{${"gameType"}}`, encodeURIComponent(String(gameType)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 스코어 갱신
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {ScoreRequestDto} requestDto requestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateScoreUsingPATCH: async (gameType: 'GAME_KARROT' | 'GAME_2048', requestDto: ScoreRequestDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'gameType' is not null or undefined
            assertParamExists('updateScoreUsingPATCH', 'gameType', gameType)
            // verify required parameter 'requestDto' is not null or undefined
            assertParamExists('updateScoreUsingPATCH', 'requestDto', requestDto)
            const localVarPath = `/api/games/{gameType}/score`
                .replace(`{${"gameType"}}`, encodeURIComponent(String(gameType)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GamePlayApi - functional programming interface
 * @export
 */
export const GamePlayApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GamePlayApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 한마디 추가
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {CommentRequestDto} requestDto requestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addCommentUsingPATCH(gameType: 'GAME_KARROT' | 'GAME_2048', requestDto: CommentRequestDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseUnit>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addCommentUsingPATCH(gameType, requestDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 2시간 내에 플레이한 유저 수
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserCountByDailyUsingGET(gameType: 'GAME_KARROT' | 'GAME_2048', options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseint>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserCountByDailyUsingGET(gameType, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 플레이
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async playGameUsingPOST(gameType: 'GAME_KARROT' | 'GAME_2048', options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseUnit>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.playGameUsingPOST(gameType, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 스코어 갱신
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {ScoreRequestDto} requestDto requestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateScoreUsingPATCH(gameType: 'GAME_KARROT' | 'GAME_2048', requestDto: ScoreRequestDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseUnit>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateScoreUsingPATCH(gameType, requestDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * GamePlayApi - factory interface
 * @export
 */
export const GamePlayApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GamePlayApiFp(configuration)
    return {
        /**
         * 
         * @summary 한마디 추가
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {CommentRequestDto} requestDto requestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addCommentUsingPATCH(gameType: 'GAME_KARROT' | 'GAME_2048', requestDto: CommentRequestDto, options?: any): AxiosPromise<BaseResponseUnit> {
            return localVarFp.addCommentUsingPATCH(gameType, requestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 2시간 내에 플레이한 유저 수
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserCountByDailyUsingGET(gameType: 'GAME_KARROT' | 'GAME_2048', options?: any): AxiosPromise<BaseResponseint> {
            return localVarFp.getUserCountByDailyUsingGET(gameType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 플레이
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        playGameUsingPOST(gameType: 'GAME_KARROT' | 'GAME_2048', options?: any): AxiosPromise<BaseResponseUnit> {
            return localVarFp.playGameUsingPOST(gameType, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 스코어 갱신
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {ScoreRequestDto} requestDto requestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateScoreUsingPATCH(gameType: 'GAME_KARROT' | 'GAME_2048', requestDto: ScoreRequestDto, options?: any): AxiosPromise<BaseResponseUnit> {
            return localVarFp.updateScoreUsingPATCH(gameType, requestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GamePlayApi - object-oriented interface
 * @export
 * @class GamePlayApi
 * @extends {BaseAPI}
 */
export class GamePlayApi extends BaseAPI {
    /**
     * 
     * @summary 한마디 추가
     * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
     * @param {CommentRequestDto} requestDto requestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamePlayApi
     */
    public addCommentUsingPATCH(gameType: 'GAME_KARROT' | 'GAME_2048', requestDto: CommentRequestDto, options?: AxiosRequestConfig) {
        return GamePlayApiFp(this.configuration).addCommentUsingPATCH(gameType, requestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 2시간 내에 플레이한 유저 수
     * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamePlayApi
     */
    public getUserCountByDailyUsingGET(gameType: 'GAME_KARROT' | 'GAME_2048', options?: AxiosRequestConfig) {
        return GamePlayApiFp(this.configuration).getUserCountByDailyUsingGET(gameType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 플레이
     * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamePlayApi
     */
    public playGameUsingPOST(gameType: 'GAME_KARROT' | 'GAME_2048', options?: AxiosRequestConfig) {
        return GamePlayApiFp(this.configuration).playGameUsingPOST(gameType, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 스코어 갱신
     * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
     * @param {ScoreRequestDto} requestDto requestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GamePlayApi
     */
    public updateScoreUsingPATCH(gameType: 'GAME_KARROT' | 'GAME_2048', requestDto: ScoreRequestDto, options?: AxiosRequestConfig) {
        return GamePlayApiFp(this.configuration).updateScoreUsingPATCH(gameType, requestDto, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * GameTownApi - axios parameter creator
 * @export
 */
export const GameTownApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 동네 리더보드 조회
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {number} [month] month
         * @param {number} [size] size
         * @param {number} [week] week
         * @param {number} [year] year
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLeaderBoardByTownUsingGET: async (gameType: 'GAME_KARROT' | 'GAME_2048', month?: number, size?: number, week?: number, year?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'gameType' is not null or undefined
            assertParamExists('getLeaderBoardByTownUsingGET', 'gameType', gameType)
            const localVarPath = `/api/games/{gameType}/towns/leaderboard`
                .replace(`{${"gameType"}}`, encodeURIComponent(String(gameType)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (month !== undefined) {
                localVarQueryParameter['month'] = month;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (week !== undefined) {
                localVarQueryParameter['week'] = week;
            }

            if (year !== undefined) {
                localVarQueryParameter['year'] = year;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GameTownApi - functional programming interface
 * @export
 */
export const GameTownApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GameTownApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 동네 리더보드 조회
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {number} [month] month
         * @param {number} [size] size
         * @param {number} [week] week
         * @param {number} [year] year
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLeaderBoardByTownUsingGET(gameType: 'GAME_KARROT' | 'GAME_2048', month?: number, size?: number, week?: number, year?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseListTownRankingDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLeaderBoardByTownUsingGET(gameType, month, size, week, year, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * GameTownApi - factory interface
 * @export
 */
export const GameTownApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GameTownApiFp(configuration)
    return {
        /**
         * 
         * @summary 동네 리더보드 조회
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {number} [month] month
         * @param {number} [size] size
         * @param {number} [week] week
         * @param {number} [year] year
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLeaderBoardByTownUsingGET(gameType: 'GAME_KARROT' | 'GAME_2048', month?: number, size?: number, week?: number, year?: number, options?: any): AxiosPromise<BaseResponseListTownRankingDto> {
            return localVarFp.getLeaderBoardByTownUsingGET(gameType, month, size, week, year, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GameTownApi - object-oriented interface
 * @export
 * @class GameTownApi
 * @extends {BaseAPI}
 */
export class GameTownApi extends BaseAPI {
    /**
     * 
     * @summary 동네 리더보드 조회
     * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
     * @param {number} [month] month
     * @param {number} [size] size
     * @param {number} [week] week
     * @param {number} [year] year
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameTownApi
     */
    public getLeaderBoardByTownUsingGET(gameType: 'GAME_KARROT' | 'GAME_2048', month?: number, size?: number, week?: number, year?: number, options?: AxiosRequestConfig) {
        return GameTownApiFp(this.configuration).getLeaderBoardByTownUsingGET(gameType, month, size, week, year, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * GameUserApi - axios parameter creator
 * @export
 */
export const GameUserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 유저 리더보드 조회
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {number} [month] month
         * @param {number} [size] size
         * @param {number} [week] week
         * @param {number} [year] year
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLeaderBoardByUserUsingGET: async (gameType: 'GAME_KARROT' | 'GAME_2048', month?: number, size?: number, week?: number, year?: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'gameType' is not null or undefined
            assertParamExists('getLeaderBoardByUserUsingGET', 'gameType', gameType)
            const localVarPath = `/api/games/{gameType}/users/leaderboard`
                .replace(`{${"gameType"}}`, encodeURIComponent(String(gameType)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (month !== undefined) {
                localVarQueryParameter['month'] = month;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (week !== undefined) {
                localVarQueryParameter['week'] = week;
            }

            if (year !== undefined) {
                localVarQueryParameter['year'] = year;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 내 현재/최고 랭킹(점수) 정보 조회
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {'BEST' | 'CURRENT'} [type] type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyRankInfoUsingGET: async (gameType: 'GAME_KARROT' | 'GAME_2048', type?: 'BEST' | 'CURRENT', options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'gameType' is not null or undefined
            assertParamExists('getMyRankInfoUsingGET', 'gameType', gameType)
            const localVarPath = `/api/games/{gameType}/users/me/ranking`
                .replace(`{${"gameType"}}`, encodeURIComponent(String(gameType)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GameUserApi - functional programming interface
 * @export
 */
export const GameUserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GameUserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 유저 리더보드 조회
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {number} [month] month
         * @param {number} [size] size
         * @param {number} [week] week
         * @param {number} [year] year
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLeaderBoardByUserUsingGET(gameType: 'GAME_KARROT' | 'GAME_2048', month?: number, size?: number, week?: number, year?: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseListUserRankingDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLeaderBoardByUserUsingGET(gameType, month, size, week, year, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 내 현재/최고 랭킹(점수) 정보 조회
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {'BEST' | 'CURRENT'} [type] type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMyRankInfoUsingGET(gameType: 'GAME_KARROT' | 'GAME_2048', type?: 'BEST' | 'CURRENT', options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseRankingDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMyRankInfoUsingGET(gameType, type, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * GameUserApi - factory interface
 * @export
 */
export const GameUserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GameUserApiFp(configuration)
    return {
        /**
         * 
         * @summary 유저 리더보드 조회
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {number} [month] month
         * @param {number} [size] size
         * @param {number} [week] week
         * @param {number} [year] year
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLeaderBoardByUserUsingGET(gameType: 'GAME_KARROT' | 'GAME_2048', month?: number, size?: number, week?: number, year?: number, options?: any): AxiosPromise<BaseResponseListUserRankingDto> {
            return localVarFp.getLeaderBoardByUserUsingGET(gameType, month, size, week, year, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 내 현재/최고 랭킹(점수) 정보 조회
         * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
         * @param {'BEST' | 'CURRENT'} [type] type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMyRankInfoUsingGET(gameType: 'GAME_KARROT' | 'GAME_2048', type?: 'BEST' | 'CURRENT', options?: any): AxiosPromise<BaseResponseRankingDto> {
            return localVarFp.getMyRankInfoUsingGET(gameType, type, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GameUserApi - object-oriented interface
 * @export
 * @class GameUserApi
 * @extends {BaseAPI}
 */
export class GameUserApi extends BaseAPI {
    /**
     * 
     * @summary 유저 리더보드 조회
     * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
     * @param {number} [month] month
     * @param {number} [size] size
     * @param {number} [week] week
     * @param {number} [year] year
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameUserApi
     */
    public getLeaderBoardByUserUsingGET(gameType: 'GAME_KARROT' | 'GAME_2048', month?: number, size?: number, week?: number, year?: number, options?: AxiosRequestConfig) {
        return GameUserApiFp(this.configuration).getLeaderBoardByUserUsingGET(gameType, month, size, week, year, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 내 현재/최고 랭킹(점수) 정보 조회
     * @param {'GAME_KARROT' | 'GAME_2048'} gameType gameType
     * @param {'BEST' | 'CURRENT'} [type] type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GameUserApi
     */
    public getMyRankInfoUsingGET(gameType: 'GAME_KARROT' | 'GAME_2048', type?: 'BEST' | 'CURRENT', options?: AxiosRequestConfig) {
        return GameUserApiFp(this.configuration).getMyRankInfoUsingGET(gameType, type, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * NotificationApi - axios parameter creator
 * @export
 */
export const NotificationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 알림 신청 여부 확인
         * @param {'OPEN_REGION' | 'OPEN_GAME' | 'SUBSCRIBE_OFF'} type type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkNotificationUsingGET: async (type: 'OPEN_REGION' | 'OPEN_GAME' | 'SUBSCRIBE_OFF', options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'type' is not null or undefined
            assertParamExists('checkNotificationUsingGET', 'type', type)
            const localVarPath = `/api/notifications/check`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 알림 신청(지역 오픈/게임 오픈)
         * @param {NotificationRequestDto} requestDto requestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveNotificationUsingPOST: async (requestDto: NotificationRequestDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestDto' is not null or undefined
            assertParamExists('saveNotificationUsingPOST', 'requestDto', requestDto)
            const localVarPath = `/api/notifications`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NotificationApi - functional programming interface
 * @export
 */
export const NotificationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NotificationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 알림 신청 여부 확인
         * @param {'OPEN_REGION' | 'OPEN_GAME' | 'SUBSCRIBE_OFF'} type type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async checkNotificationUsingGET(type: 'OPEN_REGION' | 'OPEN_GAME' | 'SUBSCRIBE_OFF', options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseNotificationCheckDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.checkNotificationUsingGET(type, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary 알림 신청(지역 오픈/게임 오픈)
         * @param {NotificationRequestDto} requestDto requestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async saveNotificationUsingPOST(requestDto: NotificationRequestDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseUnit>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.saveNotificationUsingPOST(requestDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * NotificationApi - factory interface
 * @export
 */
export const NotificationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NotificationApiFp(configuration)
    return {
        /**
         * 
         * @summary 알림 신청 여부 확인
         * @param {'OPEN_REGION' | 'OPEN_GAME' | 'SUBSCRIBE_OFF'} type type
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        checkNotificationUsingGET(type: 'OPEN_REGION' | 'OPEN_GAME' | 'SUBSCRIBE_OFF', options?: any): AxiosPromise<BaseResponseNotificationCheckDto> {
            return localVarFp.checkNotificationUsingGET(type, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 알림 신청(지역 오픈/게임 오픈)
         * @param {NotificationRequestDto} requestDto requestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        saveNotificationUsingPOST(requestDto: NotificationRequestDto, options?: any): AxiosPromise<BaseResponseUnit> {
            return localVarFp.saveNotificationUsingPOST(requestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NotificationApi - object-oriented interface
 * @export
 * @class NotificationApi
 * @extends {BaseAPI}
 */
export class NotificationApi extends BaseAPI {
    /**
     * 
     * @summary 알림 신청 여부 확인
     * @param {'OPEN_REGION' | 'OPEN_GAME' | 'SUBSCRIBE_OFF'} type type
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationApi
     */
    public checkNotificationUsingGET(type: 'OPEN_REGION' | 'OPEN_GAME' | 'SUBSCRIBE_OFF', options?: AxiosRequestConfig) {
        return NotificationApiFp(this.configuration).checkNotificationUsingGET(type, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 알림 신청(지역 오픈/게임 오픈)
     * @param {NotificationRequestDto} requestDto requestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NotificationApi
     */
    public saveNotificationUsingPOST(requestDto: NotificationRequestDto, options?: AxiosRequestConfig) {
        return NotificationApiFp(this.configuration).saveNotificationUsingPOST(requestDto, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * Oauth2Api - axios parameter creator
 * @export
 */
export const Oauth2ApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 당근 Oauth2
         * @param {KarrotCodeRequestDto} requestDto requestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        karrotLoginUsingPOST: async (requestDto: KarrotCodeRequestDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestDto' is not null or undefined
            assertParamExists('karrotLoginUsingPOST', 'requestDto', requestDto)
            const localVarPath = `/api/oauth`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * Oauth2Api - functional programming interface
 * @export
 */
export const Oauth2ApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = Oauth2ApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 당근 Oauth2
         * @param {KarrotCodeRequestDto} requestDto requestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async karrotLoginUsingPOST(requestDto: KarrotCodeRequestDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseTokenDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.karrotLoginUsingPOST(requestDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * Oauth2Api - factory interface
 * @export
 */
export const Oauth2ApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = Oauth2ApiFp(configuration)
    return {
        /**
         * 
         * @summary 당근 Oauth2
         * @param {KarrotCodeRequestDto} requestDto requestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        karrotLoginUsingPOST(requestDto: KarrotCodeRequestDto, options?: any): AxiosPromise<BaseResponseTokenDto> {
            return localVarFp.karrotLoginUsingPOST(requestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Oauth2Api - object-oriented interface
 * @export
 * @class Oauth2Api
 * @extends {BaseAPI}
 */
export class Oauth2Api extends BaseAPI {
    /**
     * 
     * @summary 당근 Oauth2
     * @param {KarrotCodeRequestDto} requestDto requestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof Oauth2Api
     */
    public karrotLoginUsingPOST(requestDto: KarrotCodeRequestDto, options?: AxiosRequestConfig) {
        return Oauth2ApiFp(this.configuration).karrotLoginUsingPOST(requestDto, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * RegionApi - axios parameter creator
 * @export
 */
export const RegionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary RegionId로 지역 정보 조회
         * @param {string} regionId regionId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTownInfoUsingGET: async (regionId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'regionId' is not null or undefined
            assertParamExists('getTownInfoUsingGET', 'regionId', regionId)
            const localVarPath = `/api/region`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (regionId !== undefined) {
                localVarQueryParameter['regionId'] = regionId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RegionApi - functional programming interface
 * @export
 */
export const RegionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RegionApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary RegionId로 지역 정보 조회
         * @param {string} regionId regionId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTownInfoUsingGET(regionId: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseRegionDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTownInfoUsingGET(regionId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * RegionApi - factory interface
 * @export
 */
export const RegionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RegionApiFp(configuration)
    return {
        /**
         * 
         * @summary RegionId로 지역 정보 조회
         * @param {string} regionId regionId
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTownInfoUsingGET(regionId: string, options?: any): AxiosPromise<BaseResponseRegionDto> {
            return localVarFp.getTownInfoUsingGET(regionId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RegionApi - object-oriented interface
 * @export
 * @class RegionApi
 * @extends {BaseAPI}
 */
export class RegionApi extends BaseAPI {
    /**
     * 
     * @summary RegionId로 지역 정보 조회
     * @param {string} regionId regionId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RegionApi
     */
    public getTownInfoUsingGET(regionId: string, options?: AxiosRequestConfig) {
        return RegionApiFp(this.configuration).getTownInfoUsingGET(regionId, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * SurveyApi - axios parameter creator
 * @export
 */
export const SurveyApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 하고 싶은 게임 등록
         * @param {SurveyRequestDto} requestDto requestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerGameSurveyUsingPOST: async (requestDto: SurveyRequestDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestDto' is not null or undefined
            assertParamExists('registerGameSurveyUsingPOST', 'requestDto', requestDto)
            const localVarPath = `/api/surveys`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SurveyApi - functional programming interface
 * @export
 */
export const SurveyApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SurveyApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 하고 싶은 게임 등록
         * @param {SurveyRequestDto} requestDto requestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async registerGameSurveyUsingPOST(requestDto: SurveyRequestDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseUnit>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.registerGameSurveyUsingPOST(requestDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SurveyApi - factory interface
 * @export
 */
export const SurveyApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SurveyApiFp(configuration)
    return {
        /**
         * 
         * @summary 하고 싶은 게임 등록
         * @param {SurveyRequestDto} requestDto requestDto
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        registerGameSurveyUsingPOST(requestDto: SurveyRequestDto, options?: any): AxiosPromise<BaseResponseUnit> {
            return localVarFp.registerGameSurveyUsingPOST(requestDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SurveyApi - object-oriented interface
 * @export
 * @class SurveyApi
 * @extends {BaseAPI}
 */
export class SurveyApi extends BaseAPI {
    /**
     * 
     * @summary 하고 싶은 게임 등록
     * @param {SurveyRequestDto} requestDto requestDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SurveyApi
     */
    public registerGameSurveyUsingPOST(requestDto: SurveyRequestDto, options?: AxiosRequestConfig) {
        return SurveyApiFp(this.configuration).registerGameSurveyUsingPOST(requestDto, options).then((request) => request(this.axios, this.basePath));
    }
}


/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 내 정보 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserInfoUsingGET: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication JWT required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 내 정보 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserInfoUsingGET(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseUserDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserInfoUsingGET(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary 내 정보 조회
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserInfoUsingGET(options?: any): AxiosPromise<BaseResponseUserDto> {
            return localVarFp.getUserInfoUsingGET(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @summary 내 정보 조회
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getUserInfoUsingGET(options?: AxiosRequestConfig) {
        return UserApiFp(this.configuration).getUserInfoUsingGET(options).then((request) => request(this.axios, this.basePath));
    }
}


