name: Main-branch (Production) deploy actions
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      REACT_APP_BASE_URL: ${{secrets.REACT_APP_BASE_URL_PRODUCTION}}
      REACT_APP_APP_ID: ${{secrets.REACT_APP_APP_ID_PRODUCTION}}
      REACT_APP_MINI_PRESET: ${{secrets.REACT_APP_MINI_PRESET_PRODUCTION}}
      REACT_APP_MINI_INSTALLATION_URL: ${{secrets.REACT_APP_MINI_INSTALLATION_URL_PRODUCTION}}
      REACT_APP_FIREBASE_API_KEY: ${{secrets.REACT_APP_FIREBASE_API_KEY_PRODUCTION}}
      REACT_APP_FIREBASE_AUTH_DOMAIN: ${{secrets.REACT_APP_FIREBASE_AUTH_DOMAIN_PRODUCTION}}
      REACT_APP_FIREBASE_PROJECT_ID: ${{secrets.REACT_APP_FIREBASE_PROJECT_ID_PRODUCTION}}
      REACT_APP_FIREBASE_STORAGE_BUCKET: ${{secrets.REACT_APP_FIREBASE_STORAGE_BUCKET_PRODUCTION}}
      REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID_PRODUCTION}}
      REACT_APP_FIREBASE_APP_ID: ${{secrets.REACT_APP_FIREBASE_APP_ID_PRODUCTION}}
      REACT_APP_FIREBASE_MEASUREMENT_ID: ${{secrets.REACT_APP_FIREBASE_MEASUREMENT_ID_PRODUCTION}}
          
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: CI=false npm run build

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete  
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ap-northeast-2
          AWS_S3_BUCKET: ${{secrets.AWS_S3_BUCKET_PRODUCTION}}
          SOURCE_DIR: 'build'
  
          
      - name: Invalidate CloudFront Cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ap-northeast-2
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID_PRODUCTION }}
          PATHS: '/*'
